---
# - name: Install
#   kewlfft.aur.aur:
#     use: yay
#     name:
#       - lazydocker

- name: Install
  shell: |
       /usr/local/go/bin/go install github.com/jesseduffield/lazydocker@latest
  become: true