- name: Install system packages (apt)
  apt: 
    name: ["curl", "htop", "unzip", "tmux", "lsof", "tree", "tldr", "fzf", "python3-pip", "neofetch", "ripgrep", "bat"]
  tags:
    - install
    - core
    - apt
