---
- name: Existing install
  ansible.builtin.stat:
    path: "/usr/local/go"
  register: install

- name: Download
  ansible.builtin.get_url:
    dest: /tmp/
    mode: 0755
    url: https://go.dev/dl/go1.18.linux-amd64.tar.gz
  when: not install.stat.exists

- name: Install
  ansible.builtin.shell: >
    tar -C /usr/local -xzf /tmp/go1.18.linux-amd64.tar.gz
  become: true
  when: not install.stat.exists

