---
# - name: Install
#   ansible.builtin.package:
#     name:
#       - go
#     state: latest
#   become: yes

- name: Install
  shell: |
       wget -O /tmp/go1.17.6.linux-amd64.tar.gz "https://go.dev/dl/go1.17.6.linux-amd64.tar.gz"
       rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go1.17.6.linux-amd64.tar.gz
  become: true
