- hosts: localhost
  gather_facts: true
  become: true

  pre_tasks:
  - name: Update apt repositories
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
    - include: playbooks/core-setup.yml
    - include: playbooks/zsh-setup.yml
    - include: playbooks/nvim-setup.yml
    - include: playbooks/install-aws-cli.yml
    - include: playbooks/dotfiles.yml
      #- include: playbooks/node-setup.yml

